export const dinheiro = {
    0: [
        { min: 1, max: 30, parametros: { quantDados: 0, riqueza: false } },
        { min: 31, max: 70, parametros: { quantDados: 1, ladoDados: 6, modificador: 0, multiplicador: 10, moeda: "TC", riqueza: false } },
        { min: 71, max: 95, parametros: { quantDados: 1, ladoDados: 4, modificador: 0, multiplicador: 100, moeda: "TC", riqueza: false } },
        { min: 96, max: 100, parametros: { quantDados: 1, ladoDados: 4, modificador: 0, multiplicador: 10, moeda: "T$", riqueza: false } },
    ],
    1: [
        { min: 1, max: 25, parametros: { quantDados: 0, riqueza: false } },
        { min: 26, max: 70, parametros: { quantDados: 2, ladoDados: 6, modificador: 0, multiplicador: 10, moeda: "TC", riqueza: false } },
        { min: 71, max: 95, parametros: { quantDados: 2, ladoDados: 8, modificador: 0, multiplicador: 10, moeda: "T$", riqueza: false } },
        { min: 96, max: 100, parametros: { quantDados: 1, ladoDados: 4, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
    ],
    2: [
        { min: 1, max: 20, parametros: { quantDados: 0, riqueza: false } },
        { min: 21, max: 70, parametros: { quantDados: 3, ladoDados: 8, modificador: 0, multiplicador: 10, moeda: "T$", riqueza: false } },
        { min: 71, max: 95, parametros: { quantDados: 4, ladoDados: 12, modificador: 0, multiplicador: 10, moeda: "T$", riqueza: false } },
        { min: 96, max: 100, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 0, tamanho: "menor", riqueza: true } },
    ],
    3: [
        { min: 1, max: 15, parametros: { quantDados: 0, riqueza: false } },
        { min: 16, max: 55, parametros: { quantDados: 3, ladoDados: 10, modificador: 0, multiplicador: 10, moeda: "T$", riqueza: false } },
        { min: 56, max: 85, parametros: { quantDados: 2, ladoDados: 4, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 86, max: 95, parametros: { quantDados: 2, ladoDados: 6, modificador: 1, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 96, max: 100, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 0, tamanho: "menor", riqueza: true } },
    ],
    4: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 20, parametros: { quantDados: 4, ladoDados: 12, modificador: 0, multiplicador: 10, moeda: "T$", riqueza: false } },
        { min: 21, max: 60, parametros: { quantDados: 1, ladoDados: 4, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 61, max: 90, parametros: { quantDados: 1, ladoDados: 8, modificador: 0, multiplicador: 10, moeda: "TO", riqueza: false } },
        { min: 91, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 0, modificadorJog: 0, tamanho: "menor", riqueza: true } },
    ],
    5: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 50, parametros: { quantDados: 1, ladoDados: 6, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 51, max: 80, parametros: { quantDados: 1, ladoDados: 12, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 81, max: 90, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 20, tamanho: "menor", riqueza: true } },
        { min: 91, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 20, tamanho: "menor", riqueza: true } },
    ],
    6: [
        { min: 1, max: 15, parametros: { quantDados: 0, riqueza: false } },
        { min: 16, max: 65, parametros: { quantDados: 1, ladoDados: 8, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 66, max: 95, parametros: { quantDados: 3, ladoDados: 4, modificador: 0, multiplicador: 10, moeda: "TO", riqueza: false } },
        { min: 96, max: 100, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 0, tamanho: "media", riqueza: true } },
    ],
    7: [
        { min: 1, max: 15, parametros: { quantDados: 0, riqueza: false } },
        { min: 16, max: 60, parametros: { quantDados: 2, ladoDados: 6, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 61, max: 90, parametros: { quantDados: 2, ladoDados: 10, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 91, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 0, tamanho: "menor", riqueza: true } },
    ],
    8: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 60, parametros: { quantDados: 2, ladoDados: 8, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 61, max: 90, parametros: { quantDados: 2, ladoDados: 12, modificador: 0, multiplicador: 10, moeda: "TO", riqueza: false } },
        { min: 91, max: 100, parametros: { quantDados: 1, ladoDados: 4, modificador: 1, modificadorJog: 0, tamanho: "menor", riqueza: true } },
    ],
    9: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 55, parametros: { quantDados: 2, ladoDados: 10, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 56, max: 95, parametros: { quantDados: 1, ladoDados: 4, modificador: 1, modificadorJog: 0, tamanho: "menor", riqueza: true } },
        { min: 96, max: 100, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 20, tamanho: "media", riqueza: true } },
    ],
    10: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 35, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 0, tamanho: "media", riqueza: true } },
        { min: 36, max: 85, parametros: { quantDados: 4, ladoDados: 6, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 86, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 0, modificadorJog: 0, tamanho: "media", riqueza: true } },
    ],
    11: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 30, parametros: { quantDados: 4, ladoDados: 6, modificador: 0, multiplicador: 100, moeda: "T$", riqueza: false } },
        { min: 31, max: 85, parametros: { quantDados: 4, ladoDados: 10, modificador: 0, multiplicador: 10, moeda: "TO", riqueza: false } },
        { min: 86, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 0, tamanho: "media", riqueza: true } },
    ],
    12: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 45, parametros: { quantDados: 2, ladoDados: 4, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 46, max: 85, parametros: { quantDados: 1, ladoDados: 3, modificador: 0, modificadorJog: 0, tamanho: "media", riqueza: true } },
        { min: 86, max: 100, parametros: { quantDados: 2, ladoDados: 6, modificador: 0, multiplicador: 100, moeda: "TO", riqueza: false } },
    ],
    13: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 45, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 20, tamanho: "media", riqueza: true } },
        { min: 46, max: 80, parametros: { quantDados: 2, ladoDados: 6, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 81, max: 100, parametros: { quantDados: 1, ladoDados: 4, modificador: 1, modificadorJog: 0, tamanho: "media", riqueza: true } },
    ],
    14: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 45, parametros: { quantDados: 4, ladoDados: 4, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 46, max: 80, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 0, tamanho: "media", riqueza: true } },
        { min: 81, max: 100, parametros: { quantDados: 4, ladoDados: 6, modificador: 0, multiplicador: 100, moeda: "TO", riqueza: false } },
    ],
    15: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 45, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 0, tamanho: "media", riqueza: true } },
        { min: 46, max: 80, parametros: { quantDados: 3, ladoDados: 6, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 81, max: 100, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 0, tamanho: "maior", riqueza: true } },
    ],
    16: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 45, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 20, tamanho: "media", riqueza: true } },
        { min: 46, max: 80, parametros: { quantDados: 2, ladoDados: 10, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 81, max: 100, parametros: { quantDados: 1, ladoDados: 4, modificador: 0, multiplicador: 1000, moeda: "TO", riqueza: false } },
    ],
    17: [
        { min: 1, max: 10, parametros: { quantDados: 0, riqueza: false } },
        { min: 11, max: 40, parametros: { quantDados: 3, ladoDados: 6, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 41, max: 75, parametros: { quantDados: 3, ladoDados: 10, modificador: 0, multiplicador: 100, moeda: "TO", riqueza: false } },
        { min: 76, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 0, modificadorJog: 0, tamanho: "maior", riqueza: true } },
    ],
    18: [
        { min: 1, max: 5, parametros: { quantDados: 0, riqueza: false } },
        { min: 6, max: 40, parametros: { quantDados: 4, ladoDados: 6, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 41, max: 75, parametros: { quantDados: 1, ladoDados: 3, modificador: 0, modificadorJog: 0, tamanho: "media", riqueza: true } },
        { min: 76, max: 100, parametros: { quantDados: 2, ladoDados: 4, modificador: 0, multiplicador: 1000, moeda: "TO", riqueza: false } },
    ],
    19: [
        { min: 1, max: 5, parametros: { quantDados: 0, riqueza: false } },
        { min: 6, max: 40, parametros: { quantDados: 4, ladoDados: 10, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 41, max: 75, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 0, tamanho: "maior", riqueza: true } },
        { min: 76, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 0, tamanho: "maior", riqueza: true } },
    ],
    20: [
        { min: 1, max: 5, parametros: { quantDados: 0, riqueza: false } },
        { min: 6, max: 40, parametros: { quantDados: 4, ladoDados: 12, modificador: 0, multiplicador: 1000, moeda: "T$", riqueza: false } },
        { min: 41, max: 75, parametros: { quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 20, tamanho: "maior", riqueza: true } },
        { min: 76, max: 100, parametros: { quantDados: 1, ladoDados: 12, modificador: 0, multiplicador: 1000, moeda: "TO", riqueza: false } },
    ],
    21: [
        { min: 1, max: 5, parametros: { quantDados: 0, riqueza: false } },
        { min: 6, max: 40, parametros: { quantDados: 2, ladoDados: 4, modificador: 0, multiplicador: 1000, moeda: "TO", riqueza: false } },
        { min: 41, max: 75, parametros: { quantDados: 1, ladoDados: 3, modificador: 0, modificadorJog: 0, tamanho: "maior", riqueza: true } },
        { min: 76, max: 100, parametros: { quantDados: 1, ladoDados: 3, modificador: 1, modificadorJog: 20, tamanho: "maior", riqueza: true } },
    ],
};

export const riquezas = {
    "menor": [
        { min: 1, max: 25, parametros: { quantDados: 4, ladoDados: 4, multiplicador: 1 } },
        { min: 26, max: 40, parametros: { quantDados: 4, ladoDados: 4, multiplicador: 1 } },
        { min: 41, max: 55, parametros: { quantDados: 2, ladoDados: 4, multiplicador: 10 } },
        { min: 56, max: 70, parametros: { quantDados: 4, ladoDados: 6, multiplicador: 10 } },
        { min: 71, max: 85, parametros: { quantDados: 1, ladoDados: 6, multiplicador: 100 } },
        { min: 86, max: 95, parametros: { quantDados: 2, ladoDados: 6, multiplicador: 100 } },
        { min: 96, max: 99, parametros: { quantDados: 2, ladoDados: 8, multiplicador: 100 } },
        { min: 100, max: 120, parametros: { quantDados: 4, ladoDados: 10, multiplicador: 100 } },
    ],
    "media": [
        { min: 1, max: 10, parametros: { quantDados: 2, ladoDados: 4, multiplicador: 10 } },
        { min: 11, max: 30, parametros: { quantDados: 4, ladoDados: 6, multiplicador: 10 } },
        { min: 31, max: 50, parametros: { quantDados: 1, ladoDados: 6, multiplicador: 100 } },
        { min: 51, max: 65, parametros: { quantDados: 2, ladoDados: 6, multiplicador: 100 } },
        { min: 66, max: 80, parametros: { quantDados: 2, ladoDados: 8, multiplicador: 100 } },
        { min: 81, max: 90, parametros: { quantDados: 4, ladoDados: 10, multiplicador: 100 } },
        { min: 91, max: 95, parametros: { quantDados: 6, ladoDados: 12, multiplicador: 100 } },
        { min: 96, max: 99, parametros: { quantDados: 2, ladoDados: 10, multiplicador: 1000 } },
        { min: 100, max: 120, parametros: { quantDados: 6, ladoDados: 8, multiplicador: 1000 } },
    ],
    "maior": [
        { min: 1, max: 5, parametros: { quantDados: 1, ladoDados: 6, multiplicador: 100 } },
        { min: 6, max: 15, parametros: { quantDados: 2, ladoDados: 6, multiplicador: 100 } },
        { min: 16, max: 25, parametros: { quantDados: 2, ladoDados: 8, multiplicador: 100 } },
        { min: 26, max: 40, parametros: { quantDados: 4, ladoDados: 10, multiplicador: 100 } },
        { min: 41, max: 60, parametros: { quantDados: 6, ladoDados: 12, multiplicador: 100 } },
        { min: 61, max: 75, parametros: { quantDados: 2, ladoDados: 10, multiplicador: 1000 } },
        { min: 76, max: 85, parametros: { quantDados: 6, ladoDados: 8, multiplicador: 1000 } },
        { min: 86, max: 95, parametros: { quantDados: 1, ladoDados: 10, multiplicador: 10000 } },
        { min: 96, max: 120, parametros: { quantDados: 4, ladoDados: 12, multiplicador: 10000 } },
    ],
};

export const tabelaItens = {
    0: [
        { min: 1, max: 50, parametros: { tipo: "nada" } },
        { min: 51, max: 75, parametros: { tipo: "diverso" } },
        { min: 76, max: 100, parametros: { tipo: "equipamento", doisseis: 1 } },
    ],
    1: [
        { min: 1, max: 45, parametros: { tipo: "nada" } },
        { min: 46, max: 70, parametros: { tipo: "diverso" } },
        { min: 71, max: 100, parametros: { tipo: "equipamento", doisseis: 1 } },
    ],
    2: [
        { min: 1, max: 40, parametros: { tipo: "nada" } },
        { min: 41, max: 65, parametros: { tipo: "diverso" } },
        { min: 66, max: 90, parametros: { tipo: "equipamento", doisseis: 1 } },
        { min: 91, max: 100, parametros: { tipo: "pocao", quantDados: 1, ladoDados: 1, modificador: 0, modificadorJog: 20 } },
    ],
    3: [
        { min: 1, max: 100, parametros: { tipo: "superior", quantMelhorias: 1, doisseis: 1 } },
    ],
};

export const tabelaItensResultados = {
    0: [
        { min: 1, max: 2, oquee: "Acido" },
        { min: 3, max: 4, oquee: "Agua benta" },
        { min: 5, max: 5, oquee: "Alaude elfico" },
        { min: 6, max: 6, oquee: "Algemas" },
        { min: 7, max: 8, oquee: "Baga-de-fogo" },
        { min: 9, max: 23, oquee: "Balsamo restaurador" },
        { min: 24, max: 24, oquee: "Bandana" },
        { min: 25, max: 25, oquee: "Bandoleira de poções" },
        { min: 26, max: 30, oquee: "Bomba" },
        { min: 31, max: 31, oquee: "Botas reforçadas" },
        { min: 32, max: 32, oquee: "Camiseta bufante" },
        { min: 33, max: 33, oquee: "Capa esvoaçante" },
        { min: 34, max: 34, oquee: "Capa pesada" },
        { min: 35, max: 35, oquee: "Casaco longo" },
        { min: 36, max: 36, oquee: "Chapeu arcano" },
        { min: 37, max: 38, oquee: "Coleção de livros" },
        { min: 39, max: 40, oquee: "Cosmetico" },
        { min: 41, max: 42, oquee: "Dente-de-dragão" },
        { min: 43, max: 43, oquee: "Enfeite de elmo" },
        { min: 44, max: 44, oquee: "Elixir do amor" },
        { min: 45, max: 46, oquee: "Equipamento de viagem" },
        { min: 47, max: 56, oquee: "Essencia de mana" },
        { min: 57, max: 57, oquee: "Estojo de disfarces" },
        { min: 58, max: 58, oquee: "Farrapos de ermitão" },
        { min: 59, max: 59, oquee: "Flauta mistica" },
        { min: 60, max: 66, oquee: "Fogo alquimico" },
        { min: 67, max: 67, oquee: "Gorro de ervas" },
        { min: 68, max: 69, oquee: "Liquen lilas" },
        { min: 70, max: 70, oquee: "Luneta" },
        { min: 71, max: 71, oquee: "Luva de pelica" },
        { min: 72, max: 73, oquee: "Maleta de medicamentos" },
        { min: 74, max: 74, oquee: "Manopla" },
        { min: 75, max: 75, oquee: "Manto eclesiastico" },
        { min: 76, max: 78, oquee: "Mochila de aventureiro" },
        { min: 79, max: 80, oquee: "Musgo purpura" },
        { min: 81, max: 81, oquee: "Organizador de pergaminhos" },
        { min: 82, max: 83, oquee: "Ossos de monstro" },
        { min: 84, max: 85, oquee: "Po de cristal" },
        { min: 86, max: 87, oquee: "Po de giz" },
        { min: 88, max: 88, oquee: "Po do desaparecimento" },
        { min: 89, max: 89, oquee: "Robe mistico" },
        { min: 90, max: 91, oquee: "Saco de sal" },
        { min: 92, max: 92, oquee: "Sapatos de carmuça" },
        { min: 93, max: 94, oquee: "Seixo de ambar" },
        { min: 95, max: 95, oquee: "Sela" },
        { min: 96, max: 96, oquee: "Tabardo" },
        { min: 97, max: 97, oquee: "Traje da corte" },
        { min: 98, max: 99, oquee: "Terra de cemiterio" },
        { min: 100, max: 100, oquee: "Veste de seda" },
    ],
    1: [
        {
            min: 1, max: 3, nome: "arma", lista: [
                { min: 1, max: 3, nome: "Adaga" },
                { min: 4, max: 5, nome: "Alabarda" },
                { min: 6, max: 7, nome: "Alfange" },
                { min: 8, max: 10, nome: "Arco curto" },
                { min: 11, max: 13, nome: "Arco longo" },
                { min: 14, max: 15, nome: "Azagaia" },
                { min: 16, max: 16, nome: "Balas (20)" },
                { min: 17, max: 18, nome: "Besta leve" },
                { min: 19, max: 20, nome: "Besta pesada" },
                { min: 21, max: 23, nome: "Bordão" },
                { min: 24, max: 24, nome: "Chicote" },
                { min: 25, max: 27, nome: "Cimitarra" },
                { min: 28, max: 30, nome: "Clava" },
                { min: 31, max: 31, nome: "Corrente de espinhos" },
                { min: 32, max: 33, nome: "Espada bastarda" },
                { min: 34, max: 38, nome: "Espada curta" },
                { min: 39, max: 43, nome: "Espada longa" },
                { min: 44, max: 46, nome: "Flechas (20)" },
                { min: 47, max: 49, nome: "Florete" },
                { min: 50, max: 51, nome: "Foice" },
                { min: 52, max: 53, nome: "Funda" },
                { min: 54, max: 55, nome: "Gadanho" },
                { min: 56, max: 56, nome: "Katana" },
                { min: 57, max: 59, nome: "Lança" },
                { min: 60, max: 60, nome: "Lança montada" },
                { min: 61, max: 63, nome: "Maça" },
                { min: 64, max: 66, nome: "Machadinha" },
                { min: 67, max: 67, nome: "Machado anão" },
                { min: 68, max: 70, nome: "Machado de batalha" },
                { min: 71, max: 73, nome: "Machado de guerra" },
                { min: 74, max: 74, nome: "Machado taurico" },
                { min: 75, max: 76, nome: "Mangual" },
                { min: 77, max: 77, nome: "Marreta" },
                { min: 78, max: 80, nome: "Martelo de guerra" },
                { min: 81, max: 83, nome: "Montante" },
                { min: 84, max: 84, nome: "Mosquete" },
                { min: 85, max: 85, nome: "Pedras (20)" },
                { min: 86, max: 88, nome: "Picareta" },
                { min: 89, max: 90, nome: "Pique" },
                { min: 91, max: 92, nome: "Pistola" },
                { min: 93, max: 93, nome: "Rede" },
                { min: 94, max: 96, nome: "Tacape" },
                { min: 97, max: 98, nome: "Tridente" },
                { min: 99, max: 100, nome: "Virotes (20)" },
            ],
        },
        {
            min: 4, max: 5, nome: "armadura", lista: [
                { min: 1, max: 5, nome: "Armadura de couro" },
                { min: 6, max: 10, nome: "Armadura de brunea" },
                { min: 11, max: 25, nome: "Armadura completa" },
                { min: 26, max: 30, nome: "Cota de malha" },
                { min: 31, max: 45, nome: "Couraça" },
                { min: 46, max: 55, nome: "Armadura de couro batido" },
                { min: 56, max: 65, nome: "Escudo leve" },
                { min: 66, max: 80, nome: "Escudo pesado" },
                { min: 81, max: 85, nome: "Gibão de peles" },
                { min: 86, max: 90, nome: "Loriga segmentada" },
                { min: 91, max: 100, nome: "Meia armadura" },
            ]
        },
        {
            min: 6, max: 6, nome: "esoterico", lista: [
                { min: 1, max: 10, nome: "Bolsa de po" },
                { min: 11, max: 25, nome: "Cajado arcano" },
                { min: 26, max: 35, nome: "Cetro elemental" },
                { min: 36, max: 42, nome: "Costela de lich" },
                { min: 43, max: 50, nome: "Dedo de ente" },
                { min: 51, max: 55, nome: "Luva de ferro" },
                { min: 56, max: 65, nome: "Medalhão de prata" },
                { min: 66, max: 75, nome: "Orbe cristalina" },
                { min: 76, max: 85, nome: "Tomo hermetico" },
                { min: 86, max: 100, nome: "Varinha arcana" },
            ]
        }
    ],
    2: [
        { min: 1, max: 1, oquee: "Abençoar alimentos", tipo: "Oleo" },
        { min: 2, max: 3, oquee: "Area escorregadia", tipo: "Granada" },
        { min: 4, max: 6, oquee: "Arma magica", tipo: "Oleo" },
        { min: 7, max: 7, oquee: "Compreensão", tipo: "Poção" },
        { min: 8, max: 15, oquee: "Curar ferimentos (2d8+2 PV)", tipo: "Poção" },
        { min: 16, max: 18, oquee: "Disfarce ilusorio", tipo: "Poção" },
        { min: 19, max: 20, oquee: "Escuridão", tipo: "Oleo" },
        { min: 21, max: 22, oquee: "Luz", tipo: "Oleo" },
        { min: 23, max: 24, oquee: "Nevoa", tipo: "Granada" },
        { min: 25, max: 26, oquee: "Primor atletico", tipo: "Poção" },
        { min: 27, max: 28, oquee: "Proteção divina", tipo: "Poção" },
        { min: 29, max: 30, oquee: "Resistencia a energia", tipo: "Poção" },
        { min: 31, max: 32, oquee: "Sono", tipo: "Poção" },
        { min: 33, max: 33, oquee: "Suporte ambiental", tipo: "Poção" },
        { min: 34, max: 34, oquee: "Tranca arcana", tipo: "Oleo" },
        { min: 35, max: 35, oquee: "Visão mistica", tipo: "Poção" },
        { min: 36, max: 36, oquee: "Vitalidade fantasma", tipo: "Poção" },
        { min: 37, max: 38, oquee: "Escudo da fe (Aprimoramento para duração cena)", tipo: "Poção" },
        { min: 39, max: 40, oquee: "Alterar tamanho", tipo: "Poção" },
        { min: 41, max: 42, oquee: "Aparencia perfeita", tipo: "Poção" },
        { min: 43, max: 43, oquee: "Armamento da natureza", tipo: "Oleo" },
        { min: 44, max: 49, oquee: "Bola de fogo", tipo: "Granada" },
        { min: 50, max: 51, oquee: "Camuflagem ilusoria", tipo: "Poção" },
        { min: 52, max: 53, oquee: "Concentração de combate (Aprimoramento para duração cena)", tipo: "Poção" },
        { min: 54, max: 62, oquee: "Curar ferimentos (4d8+4 PV)", tipo: "Poção" },
        { min: 63, max: 66, oquee: "Fisico divino", tipo: "Poção" },
        { min: 67, max: 68, oquee: "Mente divina", tipo: "Poção" },
        { min: 69, max: 70, oquee: "Metamorfose", tipo: "Poção" },
        { min: 71, max: 75, oquee: "Purificação", tipo: "Poção" },
        { min: 76, max: 77, oquee: "Velocidade", tipo: "Poção" },
        { min: 78, max: 79, oquee: "Vestimenta da fe", tipo: "Oleo" },
        { min: 80, max: 80, oquee: "Voz divina", tipo: "Poção" },
        { min: 81, max: 82, oquee: "Arma magica (Aprimoramento para bonus +3)", tipo: "Oleo" },
        { min: 83, max: 88, oquee: "Curar ferimentos (7d8+7 PV)", tipo: "Poção" },
        { min: 89, max: 89, oquee: "Fisico divino (Aprimoramento para tres atributos)", tipo: "Poção" },
        { min: 90, max: 92, oquee: "Invisibilidade (Aprimoramento para duração cena)", tipo: "Poção" },
        { min: 93, max: 96, oquee: "Bola de fogo (Aprimoramento para 10d6 de dano)", tipo: "Granada" },
        { min: 97, max: 120, oquee: "Curar ferimentos (11d8+11 PV)", tipo: "Poção" },
    ],
    3: [
        { min: 1, max: 100, nome: "ze da manga", tam: 1, especial: "nao" },
    ],
};