const nomes = {
    0: [
        "Aelric",
        "Brynhild",
        "Cedric",
        "Dagmar",
        "Elysande",
        "Faelan",
        "Gwendolyn",
        "Haldor",
        "Isolde",
        "Jareth",
        "Kaelin",
        "Lavinia",
        "Maelis",
        "Nerida",
        "Oswyn",
        "Persephone",
        "Quintus",
        "Rowena",
        "Seraphina",
        "Tavish",
        "Ulric",
        "Vivienne",
        "Walden",
        "Xanthe",
        "Yseult",
        "Zephyrus",
        "Ariadne",
        "Beowulf",
        "Cassandra",
        "Dorian",
        "Evangeline",
        "Finnian",
        "Guinevere",
        "Hadrian",
        "Iseult",
        "Jasmine",
        "Kieran",
        "Lysander",
        "Morgana",
        "Niamh",
        "Orion",
        "Phaedra",
        "Quinlan",
        "Rhiannon",
        "Sebastian",
        "Thalia",
        "Urien",
        "Valeria",
        "Wren",
        "Xavier",
        "Yara",
        "Zara",
        "Aldric",
        "Branwen",
        "Caelan",
        "Delphine",
        "Eamon",
        "Fiona",
        "Gareth",
        "Helena",
        "Ingrid",
        "Jasper",
        "Keira",
        "Lorcan",
        "Morgaine",
        "Nikolai",
        "Odette",
        "Peregrine",
        "Quorra",
        "Rhys",
        "Sabrina",
        "Theodore",
        "Una",
        "Vance",
        "Wilhelmina",
        "Xara",
        "Yvaine",
        "Zarael",
        "Aurelia",
        "Balthazar",
        "Cassia",
        "Darius",
        "Elara",
        "Fenris",
        "Giselle",
        "Hermione",
        "Ignatius",
        "Jocelyn",
        "Kaspar",
        "Liliana",
        "Marius",
        "Nerissa",
        "Ophelia",
        "Phineas",
        "Quintessa",
        "Raven",
        "Seraphim",
        "Theodora",
        "Ulysses",
        "Vespera",
        "Wolfgang",
        "Xanthia",
        "Ygraine",
        "Zephyrine"
    ],
    1: [
        "Zephyr",
        "Astraea",
        "Kairos",
        "Xanthe",
        "Jazara",
        "Lysander",
        "Thalassa",
        "Elysia",
        "Cyrus",
        "Soraya"
    ],
    2: [
        "Grimnar Martelo-de-Ferro",
        "Balin Escudo-de-Ouro",
        "Durin Pedra-dura",
        "Thror Barba-de-Ferro",
        "Gloin Machado-de-Batalha",
        "Dwalin Furiapedra",
        "Gimli Filho de Gloin",
        "Borin Machado-de-Aço",
        "Fili Forjador-de-Estrelas",
        "Kili Porta-Machado"
    ],
    3: [
        "Lírio",
        "Rosa",
        "Íris",
        "Violeta",
        "Jasmim",
        "Magnólia",
        "Dália",
        "Orquídea",
        "Camélia",
        "Hortênsia"
    ],
    4: [
        "Lindëlas",
        "Caladwen",
        "Eldarion",
        "Aerendir",
        "Celebrian",
        "Galadriel",
        "Legolas",
        "Elrond",
        "Arwen",
        "Eowyn"
    ],
    5: [
        "Grim",
        "Snag",
        "Muck",
        "Scab",
        "Fang",
        "Gnarly",
        "Sneer",
        "Maggot",
        "Wart",
        "Gobbo"
    ],
    6: [
        "Malakar",
        "Lilithandra",
        "Zephyr",
        "Calista",
        "Vespera",
        "Damien",
        "Sorin",
        "Raven",
        "Lyra",
        "Azazel"
    ],
    7: [
        "Astarius",
        "Brutius",
        "Mightius",
        "Furcius",
        "Taurius",
        "Vigilius",
        "Majestius",
        "Ferocius",
        "Dominius",
        "Valerius"
    ],
    8: [
        "Azim",
        "Zubair",
        "Aamir",
        "Rashad",
        "Jamal",
        "Javed",
        "Farid",
        "Hamid",
        "Rasheed",
        "Salim"
    ],
    10: [
        "Adamant",
        "Brimstone",
        "Crag",
        "Ember",
        "Flint",
        "Granite",
        "Obsidian",
        "Svarog",
        "Quartz",
        "Stoneheart"
    ],
    14: [
        "Aqua",
        "Marina",
        "Nereus",
        "Coralia",
        "Lorelei",
        "Triton",
        "Pearl",
        "Neptune",
        "Melusine",
        "Oceanus"
    ],
    15: [
        "Aurora",
        "Luna",
        "Iris",
        "Flora",
        "Celeste",
        "Melodia",
        "Serena",
        "Elysia",
        "Faylinn",
        "Zephyra"
    ],
    16: [
        "Aelric",
        "Brynhild",
        "Cedric",
        "Dagmar",
        "Elysande",
        "Faelan",
        "Gwendolyn",
        "Haldor",
        "Isolde",
        "Jareth",
        "Kaelin",
        "Lavinia",
        "Maelis",
        "Nerida",
        "Oswyn",
        "Persephone",
        "Quintus",
        "Rowena",
        "Seraphina",
        "Tavish",
        "Ulric",
        "Vivienne",
        "Walden",
        "Xanthe",
        "Yseult",
        "Zephyrus",
        "Ariadne",
        "Beowulf",
        "Cassandra",
        "Dorian",
        "Evangeline",
        "Finnian",
        "Guinevere",
        "Hadrian",
        "Iseult",
        "Jasmine",
        "Kieran",
        "Lysander",
        "Morgana",
        "Niamh",
        "Orion",
        "Phaedra",
        "Quinlan",
        "Rhiannon",
        "Sebastian",
        "Thalia",
        "Urien",
        "Valeria",
        "Wren",
        "Xavier",
        "Yara",
        "Zara",
        "Aldric",
        "Branwen",
        "Caelan",
        "Delphine",
        "Eamon",
        "Fiona",
        "Gareth",
        "Helena",
        "Ingrid",
        "Jasper",
        "Keira",
        "Lorcan",
        "Morgaine",
        "Nikolai",
        "Odette",
        "Peregrine",
        "Quorra",
        "Rhys",
        "Sabrina",
        "Theodore",
        "Una",
        "Vance",
        "Wilhelmina",
        "Xara",
        "Yvaine",
        "Zarael",
        "Aurelia",
        "Balthazar",
        "Cassia",
        "Darius",
        "Elara",
        "Fenris",
        "Giselle",
        "Hermione",
        "Ignatius",
        "Jocelyn",
        "Kaspar",
        "Liliana",
        "Marius",
        "Nerissa",
        "Ophelia",
        "Phineas",
        "Quintessa",
        "Raven",
        "Seraphim",
        "Theodora",
        "Ulysses",
        "Vespera",
        "Wolfgang",
        "Xanthia",
        "Ygraine",
        "Zephyrine"
    ]
};

const profissoes = [
    "Bardo",
    "Cavaleiro",
    "Feiticeiro",
    "Alquimista",
    "Arqueiro",
    "Ferreiro",
    "Ladino",
    "Necromante",
    "Druida",
    "Monge",
    "Paladino",
    "Mercador",
    "Curandeiro",
    "Armeiro",
    "Caçador",
    "Assassino",
    "Bruxo",
    "Mestre de Guilda",
    "Boticário",
    "Mestre de Armas",
    "Sacerdote",
    "Pintor",
    "Engenheiro",
    "Vidente",
    "Cartógrafo",
    "Guerreiro",
    "Arquiteto",
    "Coveiro",
    "Padeiro",
    "Bailarino",
    "Pescador",
    "Mago",
    "Astrólogo",
    "Cervejeiro",
    "Guarda Real",
    "Carpinteiro",
    "Barbeiro",
    "Músico",
    "Alfaiate",
    "Cavaleiro Errante",
    "Agricultor",
    "Caçador de Recompensas",
    "Forasteiro",
    "Herborista",
    "Acrobata",
    "Bibliotecário",
    "Caçador de Monstros",
    "Carrasco",
    "Curtidor",
    "Filósofo",
    "Serralheiro",
    "Lutador de Arena",
    "Armeiro",
    "Cervejeiro",
    "Embalsamador",
    "Geógrafo",
    "Jardineiro",
    "Malabarista",
    "Médico",
    "Navegador",
    "Poeta",
    "Vendedor Ambulante",
    "Caçador de Tesouros",
    "Banhista",
    "Coroinha",
    "Entalhador",
    "Padeiro",
    "Vaqueiro",
    "Contrabandista",
    "Mensageiro",
    "Adivinho",
    "Dançarino",
    "Guarda de Fronteira",
    "Joalheiro",
    "Oráculo",
    "Pintor",
    "Vidraceiro",
    "Dramaturgo",
    "Ermitão",
    "Hipnotizador",
    "Aio",
    "Alfaiate",
    "Cavaleiro Andante",
    "Coveiro",
    "Domador de Feras",
    "Escultor",
    "Guarda de Prisão",
    "Ladrão",
    "Marceneiro",
    "Rabino",
    "Regente",
    "Tapeceiro",
    "Cartomante",
    "Coronel",
    "Esgrimista",
    "Guardião do Templo",
    "Leiteiro",
    "Monge Guerreiro",
    "Pastor",
    "Sapateiro",
    "Torcedor",
    "Adivinho de Batalha",
    "Caixeiro Viajante",
    "Criador de Artefatos",
    "Doméstica",
    "Espião",
    "Guarda de Tesouro",
    "Lenhador",
    "Mestre de Cães",
    "Padeira",
    "Sacerdotisa",
    "Transeunte",
    "Catador de Lixo",
    "Dentista",
    "Ferreira",
    "Guarda Florestal",
    "Lutador de Rua",
    "Marinheiro",
    "Mestre de Cerimônias",
    "Padeira",
    "Sábio",
    "Trapaceiro",
    "Caçador de Relíquias",
    "Culinário",
    "Desbravador",
    "Fazendeiro",
    "Guarda-Costas",
    "Lenhador",
    "Mestre de Disfarces",
    "Pescador",
    "Salvador de Náufragos",
    "Ventríloquo",
    "Ladrão",
    "Contrabandista",
    "Assassino de Aluguel",
    "Mercenário",
    "Espião",
    "Arrombador de Cofres",
    "Punguista",
    "Chantagista",
    "Contratador de Informantes",
    "Navegador Pirata"
];

const lugares = [
    "Deheon",
    "Valkaria",
    "Bielefed",
    "Namalkah",
    "Winlla",
    "Ahlen",
    "Zakharov",
    "Pondsmania",
    "Republicas Livres de Samburdia",
    "Salistick",
    "Svalas",
    "Feudos de Trebuck",
    "Ermos Purpuras",
    "Nova Malpetrim",
    "Smokestone",
    "Tamu-ra",
    "Doherimm"
];

const caracPersonalidade = [
    "Amigável",
    "Honesto",
    "Justo",
    "Leal",
    "Sincero",
    "Construtivo",
    "Protetor",
    "Humilde",
    "Educado",
    "Bondoso",
    "Previsível",
    "Corajoso",
    "Leal",
    "Altruísta",
    "Pacífico",
    "Agradável",
    "Sensível",
    "Flexível",
    "Compassivo",
    "Generoso",
    "Compreensivo",
    "Resoluto",
    "Solidário",
    "Otimista",
    "Humano",
    "Alegre",
    "Tolerante",
    "Negociador",
    "Motivado",
    "Esperançoso",
    "Respeitoso",
    "Prudente",
    "Modesto",
    "Puro",
    "Honesto",
    "Sincero",
    "Fiel",
    "Organizado",
    "Equilibrado",
    "Responsável",
    "Pacífico",
    "Habilidoso",
    "Benevolente",
    "Calmo",
    "Carinhoso",
    "Cooperativo",
    "Disciplinado",
    "Persistente",
    "Compassivo",
    "Determinado",
    "Grato",
    "Harmonioso",
    "Gentil",
    "Correto",
    "Sábio",
    "Sereno",
    "Cruel",
    "Maldoso",
    "Desonesto",
    "Injusto",
    "Falso",
    "Destrutivo",
    "Perigoso",
    "Arrogante",
    "Grosseiro",
    "Impiedoso",
    "Imprevisível",
    "Covarde",
    "Desleal",
    "Egoísta",
    "Violento",
    "Desagradável",
    "Insensível",
    "Inflexível",
    "Vingativo",
    "Mesquinho",
    "Perverso",
    "Impulsivo",
    "Invejoso",
    "Obstinado",
    "Desprezível",
    "Desumano",
    "Amargurado",
    "Intolerante",
    "Intransigente",
    "Desanimado",
    "Ressentido",
    "Imprudente",
    "Insolente",
    "Rancoroso",
    "Preguiçoso",
    "Teimoso",
    "Furtivo",
    "Traidor",
    "Desleixado",
    "Desesperançoso",
    "Despreocupado",
    "Desordeiro",
    "Insatisfeito",
    "Impaciente",
    "Inflexível",
    "Indiferente",
    "Desorganizado",
    "Desequilibrado",
    "Irresponsável",
    "Agressivo",
    "Desajeitado",
    "Irascível",
    "Impuro"
];

const caracAparencia = [
    // Adjetivos Ruins
    "Feio",
    "Desleixado",
    "Desarrumado",
    "Enrugado",
    "Obeso",
    "Pálido",
    "Magro",
    "Descuidado",
    "Esquelético",
    "Desbotado",
    "Amarelado",
    "Sujo",
    "Cansado",
    "Rugoso",
    "Desengonçado",
    "Desproporcional",
    "Branquelo",
    "Manchado",
    "Inexpressivo",
    "Sem graça",
    "Sombrio",
    "Sinistro",
    "Desgrenhado",
    "Envelhecido",
    "Desgastado",
    "Sem atrativos",
    "Sem charme",
    "Amassado",
    "Frágil",
    "Sem vida",
    "Inestético",
    "Envelhecido",
    "Desinteressante",
    "Desengraçado",
    "Desproporcionado",
    "Desequilibrado",
    "Descolorido",
    "Desalinhado",
    "Sem brilho",
    "Sem estilo",
    "Sem elegância",
    "Sem personalidade",
    "Sem encanto",
    "Desprezível",
    "Sem carisma",
    "Inexpressivo",
    "Sem expressão",
    "Sem harmonia",
    "Sem atrativo",
    "Sem presença",
    "Desajeitado",
    "Sem sofisticação",
    "Bonito",
    "Atraente",
    "Elegante",
    "Radiante",
    "Esbelto",
    "Encantador",
    "Estiloso",
    "Deslumbrante",
    "Fascinante",
    "Sedutor",
    "Gracioso",
    "Impecável",
    "Char moso",
    "Impressionante",
    "Exuberante",
    "Sofisticado",
    "Harmonioso",
    "Cativante",
    "Env olvente",
    "Apresentável",
    "Agradável",
    "Encantador",
    "Adorável",
    "Belíssimo",
    "Elegante",
    "Refinado",
    "Estonteante",
    "Deslumbrante",
    "Radiante",
    "Atraente",
    "Deslumbrante",
    "Maravilhoso",
    "Deslumbrante",
    "Perfeito",
    "Radiante",
    "Lindo",
    "Exótico",
    "Estonteante",
    "Encantador",
    "Formoso",
    "Atraente",
    "Esbelta",
    "Encantadora",
    "Sofisticada",
    "Fascinante",
    "Deslumbrante",
    "Atrativa",
    "Elegante",
    "Char mosa",
    "Apresentável",
    "Encantadora",
    "Estonteante",
    "Agradável",
    "Belíssima",
    "Radiante"
];

const racasListadas = [
    "Humano",
    "Anão",
    "Dahllan",
    "Elfo",
    "Goblin",
    "Lefou",
    "Minotauro",
    "Qareen",
    "Hynnen",
    "Golem",
    "Kliren",
    "Medusa",
    "Osteon",
    "Sereia/Tritão",
    "Silfide",
    "Suraggel",
    "Trog"
];

let txt = window.document.getElementById("nomeGerado")
let raca
let nomeGerado
function gerarNome() {
    raca = parseInt(window.document.getElementById("raca").value);

    let indice = obterIndiceAleatorio(nomes[raca]);
    nomeGerado = nomes[raca][indice];
    txt.innerHTML = "<div class='realceTxtNpc'>Nome: </div>" + nomeGerado;
    caracteristicasDoNPC()
}

function obterIndiceAleatorio(array) {
    return Math.floor(Math.random() * array.length);
}

function caracteristicasDoNPC() {
    let racaAleatoria = racasListadas[Math.floor(Math.random() * racasListadas.length)]
    if (raca == 16) {
        txt.innerHTML += "<br><div class='realceTxtNpc'>Raça: </div>" + racaAleatoria
    }
    let idade = Math.floor(Math.random() * (80 - 16 + 1)) + 16;
    txt.innerHTML += "<br><div class='realceTxtNpc'>Idade: </div>" + idade

    let profissao = profissoes[Math.floor(Math.random() * profissoes.length)]
    txt.innerHTML += "<br><div class='realceTxtNpc'>profissão: </div>" + profissao

    let lugar = lugares[Math.floor(Math.random() * lugares.length)]
    txt.innerHTML += "<br><div class='realceTxtNpc'>Lugar de nascimento: </div>" + lugar

    txt.innerHTML += "<br><div class='realceTxtNpc'>Personalidade: </div>"
    let personalidade = [];
    for (let i = 0; i < 3; i++) {
        personalidade[i] = caracPersonalidade[Math.floor(Math.random() * caracPersonalidade.length)]
        txt.innerHTML += personalidade[i] + "; "
    }

    txt.innerHTML += "<div class='realceTxtNpc'><br>Aparencia: </div>"
    let aparencia = [];
    for (let i = 0; i < 3; i++) {
        aparencia[i] = caracAparencia[Math.floor(Math.random() * caracAparencia.length)]
        txt.innerHTML += aparencia[i] + "; "
    }

    let npc = {
        nome: nomeGerado,
        raca: racaAleatoria,
        idade: idade,
        profissao: profissao,
        lugar: lugar,
        personalidade: personalidade,
        aparencia: aparencia
    };

    localStorage.setItem('npc', JSON.stringify(npc));
}

let storedNPC = localStorage.getItem('npc');
if (storedNPC) {
    // Exibir as informações do NPC armazenadas
    let npc = JSON.parse(storedNPC);
    txt.innerHTML += "<div class='realceTxtNpc'>Nome: </div>" + npc.nome;
    txt.innerHTML += "<br><div class='realceTxtNpc'>Raça: </div>" + npc.raca;
    txt.innerHTML += "<br><div class='realceTxtNpc'>Idade: </div>" + npc.idade;
    txt.innerHTML += "<br><div class='realceTxtNpc'>Profissão: </div>" + npc.profissao;
    txt.innerHTML += "<br><div class='realceTxtNpc'>Lugar de nascimento: </div>" + npc.lugar;
    txt.innerHTML += "<br><div class='realceTxtNpc'>Personalidade: </div>" + npc.personalidade.join("; ");
    txt.innerHTML += "<br><div class='realceTxtNpc'>Aparência: </div>" + npc.aparencia.join("; ");
}